services:

  gotrip:
    container_name: gotrip
    build: ./gotrip
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_URL: jdbc:mysql://host.docker.internal:3306/go_trip?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: user
      DB_PASSWORD: user
      SPRING_SECURITY_NAME: empleado
      SPRING_SECURITY_PASSWORD: empleado123
    restart: always