services:

  gotrip:
    container_name: gotrip
    build: ./gotrip
    ports:
      - "80:8080"
    environment:
      DB_URL: jdbc:mysql://upnbp4bvbjfo0vxv:kXoUlqMw280ZEISazwbe@bsj6fhleaamwxxnbqsdl-mysql.services.clever-cloud.com:3306/bsj6fhleaamwxxnbqsdl
      DB_USER_NAME: upnbp4bvbjfo0vxv
      DB_PASSWORD: kXoUlqMw280ZEISazwbe
      SPRING_SECURITY_NAME: empleado
      SPRING_SECURITY_PASSWORD: empleado123
    restart: always